# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('item_type', models.IntegerField(choices=[(0, 'CRON_SCRIPT')])),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('last_finish_at', models.DateTimeField(null=True)),
                ('run_interval', models.IntegerField()),
                ('max_exec_time', models.IntegerField()),
                ('last_run_result', models.IntegerField(choices=[(0, 'NONE'), (1, 'OK'), (2, 'ERROR')], default=0)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_systemmonitor',
            },
        ),
    ]
