# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_bot_log',
            },
        ),
    ]
