# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('name_long', models.CharField(max_length=100, verbose_name='длинное название')),
                ('coin_type', models.CharField(max_length=100, verbose_name='тип монеты')),
                ('min_confirmation', models.IntegerField(default=0, verbose_name='MinConfirmation')),
                ('tx_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='TxFee')),
                ('is_active', models.BooleanField(default=False)),
                ('base_address', models.CharField(max_length=250, verbose_name='BaseAddress')),
            ],
            options={
                'db_table': 'trading_currency',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('min_trade_size', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='MinTradeSize')),
                ('is_active', models.BooleanField(default=False)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='trading.Currency', verbose_name='BaseCurrency')),
                ('market_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_currencies', to='trading.Currency', verbose_name='MarketCurrency')),
            ],
            options={
                'db_table': 'trading_market',
            },
        ),
        migrations.CreateModel(
            name='MarketOrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Quantity')),
                ('rate', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='rate')),
                ('type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=5)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market')),
            ],
            options={
                'db_table': 'trading_market_order_book',
            },
        ),
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DisplayMarketName')),
                ('high', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Low')),
                ('volume', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Volume')),
                ('last', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Last')),
                ('base_volume', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='BaseVolume')),
                ('bid', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Bid')),
                ('ask', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Ask')),
                ('open_by_orders', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='OpenBuyOrders')),
                ('open_sell_orders', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='OpenSellOrders')),
                ('prev_day', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='PrevDay')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market')),
            ],
            options={
                'db_table': 'trading_market_summary',
            },
        ),
    ]
