# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='base_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='BaseAddress'),
        ),
    ]
