# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20171130_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='notice',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Notice'),
        ),
    ]
