# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_currency_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together=set([('base_currency', 'market_currency')]),
        ),
    ]
