# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20171201_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketMyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Price')),
                ('amount', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Price')),
                ('spent', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Price')),
                ('type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=5)),
            ],
            options={
                'db_table': 'trading_market_order_my',
            },
        ),
        migrations.CreateModel(
            name='MarketTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(verbose_name='TimeStamp')),
                ('price', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Total')),
                ('type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=5)),
            ],
            options={
                'db_table': 'trading_market_trade',
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'валюта', 'verbose_name_plural': 'валюты'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['base_currency', 'market_currency'], 'verbose_name': 'пара', 'verbose_name_plural': 'пары'},
        ),
        migrations.AlterModelOptions(
            name='marketsummary',
            options={'verbose_name': 'Summary 24H', 'verbose_name_plural': 'Summary 24H'},
        ),
        migrations.AddField(
            model_name='market',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ADDED'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='high',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='24HR HIGH'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='last',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Last Price'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='low',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='24HR LOW'),
        ),
        migrations.AddField(
            model_name='markettrade',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market'),
        ),
        migrations.AddField(
            model_name='marketmyorder',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market'),
        ),
    ]
