# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20180102_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
