# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_marketmyorder_from_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketmyorder',
            options={'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордера'},
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='from_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketMyOrder'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='spent',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Spent'),
        ),
    ]
