# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20180104_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
