# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_marketmyorder_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='fee',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Fee'),
        ),
    ]
