# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_marketmyorder_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открытый'), ('CANCELED', 'Отменен'), ('FILLED', 'Исполнен'), ('PART_FILLED', 'Частично исполнен'), ('CLOSED', 'Закрыт')], default='OPEN', max_length=5),
        ),
    ]
