# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_marketmyorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='commission',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Комиссия', max_digits=24, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='marketmyorder',
            name='get_order_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='amount',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Кол-во', max_digits=24, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='price',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Цена покупки/продажи', max_digits=24, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='spent',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Потрачено', max_digits=24, verbose_name='Spent'),
        ),
    ]
