# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_auto_20180107_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('is_test', models.BooleanField(default=False)),
                ('max_spend', models.DecimalField(decimal_places=12, default=0, max_digits=24, verbose_name='Максимальная сумма покупки')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Currency', verbose_name='Валюта')),
            ],
            options={
                'db_table': 'trading_market_bot',
            },
        ),
    ]
