# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_auto_20180109_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='markup',
            field=models.IntegerField(default=1, help_text='процент прибаляемый к сумме покупки при продаже от 1 до 100', verbose_name='% прибыли'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='order_life_time',
            field=models.IntegerField(default=60, help_text='Количество секунд через которе будет удален неисполненный ордер на покупку', verbose_name='время жизни ордера'),
        ),
    ]
