# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20180109_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbot',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
