# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


from django.db import migrations, models
import trading.models


def add_order_bot(apps, schema_editor):
    """
    Перенесем Имена в ru
    :param apps:
    :param schema_editor:
    :return:
    """
    MarketBot = apps.get_model("trading", "MarketBot")
    MarketMyOrder = apps.get_model("trading", "MarketMyOrder")

    bot, created = MarketBot.objects.get_or_create(name='bot_ema_macd_rsi')
    if created:
        bot.is_tes = True
        bot.max_spend = 0.00013256
        bot.save()

    orders = MarketMyOrder.objects.all()

    for order in orders:
        order.bot = bot
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_auto_20180109_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketBot', verbose_name='Бот'),
        ),

        migrations.RunPython(add_order_bot),
    ]
