# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def add_tick_intervals(apps, schema_editor):
    """
    Перенесем Имена в ru
    :param apps:
    :param schema_editor:
    :return:
    """
    MarketTickInterval = apps.get_model("trading", "MarketTickInterval")

    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_ONEMIN', value='oneMin')
    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_FIVEMIN', value='fiveMin')
    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_HOUR', value='hour')
    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_THIRTYMIN', value='thirtyMin')
    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_FIFTEENMIN', value='fifteenMin')
    interval, created = MarketTickInterval.objects.get_or_create(name='TICKINTERVAL_DAY', value='Day')


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_marketmyorder_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTickInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='значение')),
            ],
            options={
                'db_table': 'trading_tick_interval',
                'verbose_name': 'интервал',
                'verbose_name_plural': 'интервалы',
            },
        ),
        migrations.RunPython(add_tick_intervals),
    ]
