# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_marketbot_tick_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_ema',
            field=models.BooleanField(default=False),
        ),
    ]
