# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_marketbot_is_ema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbot',
            name='is_ema',
            field=models.BooleanField(default=False, verbose_name='Проверять по EMA'),
        ),
    ]
