# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_auto_20180109_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbot',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=1, help_text='процент прибаляемый к сумме покупки при продаже от 1 до 100', max_digits=5, verbose_name='% прибыли'),
        ),
    ]
