# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_auto_20180109_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='min_trade_size',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='MinTradeSize'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='max_spend',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Максимальная сумма покупки'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Кол-во', max_digits=24, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='commission',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Комиссия', max_digits=24, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Цена покупки/продажи', max_digits=24, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='spent',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Потрачено', max_digits=24, verbose_name='Spent'),
        ),
        migrations.AlterField(
            model_name='marketorderbook',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='marketorderbook',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='ask',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Ask'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='base_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BaseVolume'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='bid',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Bid'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='high',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='24HR HIGH'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='last',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Last Price'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='low',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='24HR LOW'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='open_by_orders',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='OpenBuyOrders'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='open_sell_orders',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='OpenSellOrders'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='prev_day',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='PrevDay'),
        ),
        migrations.AlterField(
            model_name='marketsummary',
            name='volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='markettrade',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='markettrade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='markettrade',
            name='total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Total'),
        ),
    ]
