# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:54
from __future__ import unicode_literals

from django.db import migrations
from trading.models import MarketMyOrder


def convert_status(apps, schema_editor):
    """
    Перенесем Имена в ru
    :param apps:
    :param schema_editor:
    :return:
    """

    orders = MarketMyOrder.objects.filter(status__in=[MarketMyOrder.Status.FILLED, ],
                                          type=MarketMyOrder.Type.SELL)

    for order in orders:
        from_order = order.from_order
        from_order.status = MarketMyOrder.Status.CLOSED
        from_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_auto_20180109_1536'),
    ]

    operations = [
        # migrations.RunPython(convert_status),
    ]
