# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_auto_20180109_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='ema_fastperiod',
            field=models.SmallIntegerField(default=7, verbose_name='EMA fastperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='ema_slowperiod',
            field=models.SmallIntegerField(default=26, verbose_name='EMA slowperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_macd',
            field=models.BooleanField(default=True, verbose_name='Проверять по MACD направление'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_macd_cross_bottom_to_top',
            field=models.BooleanField(default=False, help_text='Пересекает быстрая медленную снизу вверх', verbose_name='Проверять по MACD пересечение'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_rsi',
            field=models.BooleanField(default=True, help_text='Проверяет значение больше, меньше или внутри коридора значений', verbose_name='Проверять по RSI'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='macd_fastperiod',
            field=models.SmallIntegerField(default=8, verbose_name='MACD fastperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='macd_signalperiod',
            field=models.SmallIntegerField(default=9, verbose_name='MACD signalperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='macd_slowperiod',
            field=models.SmallIntegerField(default=17, verbose_name='MACD slowperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='rsi_less',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='RSI меньше'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='rsi_more',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='RSI больше'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='rsi_timeperiod',
            field=models.SmallIntegerField(default=7, verbose_name='timeperiod'),
        ),
    ]
