# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_auto_20180110_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=8, default=0, help_text='Цена покупки/продажи', max_digits=24, verbose_name='Price')),
                ('get_order_result', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа')], default='BUY', max_length=5)),
                ('status', models.CharField(choices=[('OPEN', 'Открытый'), ('CANCELED', 'Отменен'), ('FILLED', 'Исполнен'), ('PART_FILLED', 'Частично исполнен'), ('CLOSED', 'Закрыт')], default='OPEN', max_length=25)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketBot', verbose_name='Бот')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Тестовый ордер',
                'db_table': 'trading_bot_test_order',
                'verbose_name_plural': 'Тестовые ордера',
            },
        ),
    ]
