# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_bottestorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_compare_value',
            field=models.BooleanField(default=False, verbose_name='Сравнивать объем торгов'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_green',
            field=models.BooleanField(default=False, verbose_name='Проверять по green candle'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_min_value',
            field=models.BooleanField(default=False, verbose_name='Проверять минимальный объем торгов'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_ratio_open_close',
            field=models.BooleanField(default=False, verbose_name='Сравнивать соотношение цены открытия и закрытия'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_sma',
            field=models.BooleanField(default=False, verbose_name='Проверять по SMA'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='min_value',
            field=models.SmallIntegerField(default=150, verbose_name='Минимальный объем торгов'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='ratio_open_close',
            field=models.DecimalField(decimal_places=2, default=1.03, max_digits=5, verbose_name='Коэффициент соотношения'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='sma_period',
            field=models.SmallIntegerField(default=50, verbose_name='SMA period'),
        ),
    ]
