# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_auto_20180114_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_sma_cross_bottom_to_top',
            field=models.BooleanField(default=False, help_text='Пересекает быстрая медленную снизу вверх', verbose_name='Проверять по SMA пересечение'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='sma_fastperiod',
            field=models.SmallIntegerField(default=5, verbose_name='SMA fastperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='sma_slowperiod',
            field=models.SmallIntegerField(default=20, verbose_name='SMA slowperiod'),
        ),
    ]
