# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_auto_20180116_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='adx_timeperiod',
            field=models.SmallIntegerField(default=14, verbose_name='timeperiod'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_adx',
            field=models.BooleanField(default=False, verbose_name='Проверять по ADX'),
        ),
    ]
