# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_auto_20180117_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='adx_less',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ADX меньше'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='adx_more',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ADX больше'),
        ),
    ]
