# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_auto_20180117_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_stochastic',
            field=models.BooleanField(default=False, verbose_name='Проверять по Stochastic'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stochastic_fastk_period',
            field=models.SmallIntegerField(default=5, verbose_name='Stochastic fastk_period'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stochastic_slowd_period',
            field=models.SmallIntegerField(default=3, verbose_name='Stochastic slowd_period'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stochastic_slowk_period',
            field=models.SmallIntegerField(default=3, verbose_name='Stochastic slowk_period'),
        ),
    ]
