# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_auto_20180119_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='stochastic_less',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Stochastic меньше'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stochastic_more',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Stochastic больше'),
        ),
    ]
