# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0035_marketbot_is_stochastic_cross'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_ha',
            field=models.BooleanField(default=False, verbose_name='Проверять по Heikin Ashi'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='is_stochastic',
            field=models.BooleanField(default=False, verbose_name='Проверять по Stochastic (больше/меньше)'),
        ),
    ]
