# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_auto_20180127_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_dodge',
            field=models.BooleanField(default=False, verbose_name='Проверять по dodge candle'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_fat',
            field=models.BooleanField(default=False, verbose_name='Проверять по fat candle'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_hummer',
            field=models.BooleanField(default=False, verbose_name='Проверять по hummer candle'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_simple',
            field=models.BooleanField(default=False, verbose_name='Проверять по simple candle'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_sword',
            field=models.BooleanField(default=False, verbose_name='Проверять по sword candle'),
        ),
    ]
