# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_auto_20180127_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_stochastic_fast_up',
            field=models.BooleanField(default=False, verbose_name='Проверять по Stochastic fast up'),
        ),
    ]
