# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_auto_20180129_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='coef_all_candle_max',
            field=models.SmallIntegerField(default=5.5, help_text='Влияет на: is_dodge (default=5.5)', verbose_name='COEF_ALL_CANDLE_MAX'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='coef_all_candle_mid',
            field=models.SmallIntegerField(default=3.2, help_text='Влияет на: is_fat (default=3.2)', verbose_name='COEF_ALL_CANDLE_MID'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='coef_all_candle_min',
            field=models.SmallIntegerField(default=2, help_text='Влияет на: is_fat (default=2)', verbose_name='COEF_ALL_CANDLE_MIN'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='coef_gigh_low_max',
            field=models.SmallIntegerField(default=2, help_text='Влияет на: is_fat, is_dodge (default=2)', verbose_name='COEF_HIGH_LOW_MAX'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='coef_high_low_min',
            field=models.SmallIntegerField(default=0.5, help_text='Влияет на: is_fat, is_dodge (default=0.5)', verbose_name='COEF_HIGH_LOW_MIN'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='hummer_multiplier',
            field=models.SmallIntegerField(default=2, help_text='Влияет на: is_hummer (default=2)', verbose_name='HUMMER_MULTIPLIER'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='sword_multilier',
            field=models.SmallIntegerField(default=2, help_text='Влияет на: is_sword (default=2)', verbose_name='SWORD_MULTIPLIER'),
        ),
    ]
