# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_auto_20180512_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketbot',
            name='coef_all_candle_max',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='coef_all_candle_mid',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='coef_all_candle_min',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='coef_gigh_low_max',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='coef_high_low_min',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='hummer_multiplier',
        ),
        migrations.RemoveField(
            model_name='marketbot',
            name='sword_multilier',
        ),
        migrations.AddField(
            model_name='currency',
            name='coef_all_candle_max',
            field=models.DecimalField(decimal_places=2, default=5.5, help_text='Влияет на: is_dodge (default=5.5)', max_digits=5, verbose_name='COEF_ALL_CANDLE_MAX'),
        ),
        migrations.AddField(
            model_name='currency',
            name='coef_all_candle_mid',
            field=models.DecimalField(decimal_places=2, default=3.2, help_text='Влияет на: is_fat (default=3.2)', max_digits=5, verbose_name='COEF_ALL_CANDLE_MID'),
        ),
        migrations.AddField(
            model_name='currency',
            name='coef_all_candle_min',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Влияет на: is_fat (default=2)', max_digits=5, verbose_name='COEF_ALL_CANDLE_MIN'),
        ),
        migrations.AddField(
            model_name='currency',
            name='coef_high_low_max',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Влияет на: is_fat, is_dodge (default=2)', max_digits=5, verbose_name='COEF_HIGH_LOW_MAX'),
        ),
        migrations.AddField(
            model_name='currency',
            name='coef_high_low_min',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Влияет на: is_fat, is_dodge (default=0.5)', max_digits=5, verbose_name='COEF_HIGH_LOW_MIN'),
        ),
        migrations.AddField(
            model_name='currency',
            name='hummer_multiplier',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Влияет на: is_hummer (default=2)', max_digits=5, verbose_name='HUMMER_MULTIPLIER'),
        ),
        migrations.AddField(
            model_name='currency',
            name='sword_multilier',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Влияет на: is_sword (default=2)', max_digits=5, verbose_name='SWORD_MULTIPLIER'),
        ),
    ]
