# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_auto_20180513_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='coef_level',
            field=models.DecimalField(decimal_places=8, default=0.001, help_text='Влияет на: is_dodge (default=0.001)', max_digits=24, verbose_name='выравнивающий'),
        ),
    ]
