# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0043_currency_coef_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='coef_all_candle_max',
            field=models.FloatField(default=5.5, help_text='Влияет на: is_dodge (default=5.5)', verbose_name='COEF_ALL_CANDLE_MAX'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_all_candle_mid',
            field=models.FloatField(default=3.2, help_text='Влияет на: is_fat (default=3.2)', verbose_name='COEF_ALL_CANDLE_MID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_all_candle_min',
            field=models.FloatField(default=2, help_text='Влияет на: is_fat (default=2)', verbose_name='COEF_ALL_CANDLE_MIN'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_high_low_max',
            field=models.FloatField(default=2, help_text='Влияет на: is_fat, is_dodge (default=2)', verbose_name='COEF_HIGH_LOW_MAX'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_high_low_min',
            field=models.FloatField(default=0.5, help_text='Влияет на: is_fat, is_dodge (default=0.5)', verbose_name='COEF_HIGH_LOW_MIN'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_level',
            field=models.FloatField(default=0.001, help_text='Влияет на: is_dodge (default=0.001)', verbose_name='выравнивающий'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='hummer_multiplier',
            field=models.FloatField(default=2, help_text='Влияет на: is_hummer (default=2)', verbose_name='HUMMER_MULTIPLIER'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sword_multilier',
            field=models.FloatField(default=2, help_text='Влияет на: is_sword (default=2)', verbose_name='SWORD_MULTIPLIER'),
        ),
    ]
