# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 15:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_auto_20180513_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottestorder',
            name='ticker_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketmyorder',
            name='ticker_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coef_level',
            field=models.FloatField(default=0.001, help_text='Влияет на: is_dodge (default=0,001) [ USDT - 0,001 | BTC - 0,00000001 ] ', verbose_name='выравнивающий'),
        ),
    ]
