# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_auto_20180519_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ADDED')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='DisplayMarketName')),
                ('rank', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='rank')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Market Rank',
                'verbose_name_plural': 'Markets Rank',
                'db_table': 'trading_market_rank',
            },
        ),
    ]
