# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0047_marketsummary_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_market_rank',
            field=models.BooleanField(default=False, verbose_name='Подбирать пары по рангу'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='max_rank_pairs',
            field=models.IntegerField(default=10, verbose_name='Максимальное кол-во пар'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=5, help_text='процент прибаляемый к сумме покупки при продаже от 0 до 100', max_digits=5, verbose_name='% максимальных потерь'),
        ),
    ]
