# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_auto_20180520_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='markets',
            field=models.ManyToManyField(to='trading.Market'),
        ),
    ]
