# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0049_marketbot_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbot',
            name='markets',
            field=models.ManyToManyField(blank=True, to='trading.Market', verbose_name='Пары'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=5, help_text='процент при падении рынка по достижению которого выставляется ордер на продажу', max_digits=5, verbose_name='% максимальных потерь'),
        ),
    ]
