# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from trading.models import Currency


def add_default_currency(apps, schema_editor):
    """
    Добавляем дефолтную валюту для корректного накатывания миграции
    :param apps:
    :param schema_editor:
    :return:
    """

    currencies = Currency.objects.filter(id=1)
    if currencies.count() == 0:
        Currency.objects.create(name='default', name_long='default', coin_type='default')


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0051_marketbotrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_default_currency),
        migrations.AddField(
            model_name='marketbot',
            name='base_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Currency', verbose_name='Базовая валюта'),
        ),
    ]
