# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0052_auto_20180521_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketbot',
            name='base_currency',
        ),
        migrations.AddField(
            model_name='marketbot',
            name='rank_base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Currency', verbose_name='Базовая валюта'),
        ),
    ]
