# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0053_auto_20180521_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='is_stop_loss',
            field=models.BooleanField(default=False),
        ),
    ]
