# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0054_marketmyorder_is_stop_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmyorder',
            name='from_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketMyOrder'),
        ),
    ]
