# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0055_auto_20180522_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_trailing_cost',
            field=models.BooleanField(default=False, verbose_name='Trailing cost'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='stop_loss_block_trade',
            field=models.SmallIntegerField(default=60, verbose_name='Количество минут на которое блокируется торговля после stop loss'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='trailing_cost_fall',
            field=models.DecimalField(decimal_places=2, default=1, help_text='процент падения для фиксации прибыли', max_digits=5, verbose_name='% падения'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='trailing_cost_up',
            field=models.DecimalField(decimal_places=2, default=1, help_text='процент роста после кторого фиксируем максимальную цену', max_digits=5, verbose_name='Минимальный % роста'),
        ),
    ]
