# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0056_auto_20180522_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbotrank',
            name='block_trade_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала блокировки торговли'),
        ),
        migrations.AddField(
            model_name='marketbotrank',
            name='is_block_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketbotrank',
            name='max_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='max price'),
        ),
    ]
