# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0057_auto_20180522_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketbotrank',
            options={'ordering': ['-rank'], 'verbose_name': 'Market Rank', 'verbose_name_plural': 'Markets Rank'},
        ),
        migrations.AddField(
            model_name='marketmyorder',
            name='test_spent',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Потрачено test', max_digits=24, verbose_name='Spent Test'),
        ),
        migrations.AlterField(
            model_name='marketbotrank',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_rank', to='trading.MarketBot', verbose_name='MarketBot'),
        ),
        migrations.AlterField(
            model_name='marketbotrank',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_rank', to='trading.Market', verbose_name='Market'),
        ),
    ]
