# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_auto_20180524_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ADDED')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_price', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='max price')),
                ('ticker_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('bot_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CREATE_ORDER', 'Ордер создан'), ('FILLED_ORDER', 'Ордер выполнен'), ('MAX_PRICE_FIXED', 'MaxPrice зафиксирована'), ('MAX_PRICE_UPDATED', 'MaxPrice обновлена'), ('STOP_LOSS', 'Сработал Stop Loss')], default='CREATE_ORDER', max_length=25)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.MarketBot', verbose_name='MarketBot')),
            ],
            options={
                'verbose_name': 'Order Log',
                'db_table': 'trading_market_order_log',
                'verbose_name_plural': 'Orders Log',
            },
        ),
        migrations.AddField(
            model_name='marketmyorder',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
