# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_auto_20180525_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbotrank',
            name='current_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='current price'),
        ),
    ]
