# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0061_marketbotrank_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketbotrank',
            name='current_price',
        ),
        migrations.AddField(
            model_name='marketbotrank',
            name='ticker_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
