# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0064_marketmyorder_get_order_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='trailing_stop_lost',
            field=models.DecimalField(decimal_places=2, default=1, help_text='процент падения, после которого продаем, вне зависимости от минимального процента роста', max_digits=5, verbose_name='Trailing stop loss'),
        ),
    ]
