# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0066_marketbotrank_trailing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbotrank',
            name='trailing_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='trailing price'),
        ),
        migrations.AlterField(
            model_name='marketorderlog',
            name='type',
            field=models.CharField(choices=[('CREATE_ORDER', 'Ордер создан'), ('FILLED_ORDER', 'Ордер выполнен'), ('MAX_PRICE_FIXED', 'MaxPrice зафиксирована'), ('MAX_PRICE_UPDATED', 'MaxPrice обновлена'), ('STOP_LOSS', 'Сработал Stop Loss'), ('TRAILING_FALL', 'Сработал Trailing Fall'), ('TRAILING_STOP_LOSS', 'Сработал Trailing Stop Loss'), ('STOP_LOSS', 'Установлен Stop Loss')], default='CREATE_ORDER', max_length=25),
        ),
    ]
