# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0067_auto_20180528_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketbotrank',
            name='trailing_price',
        ),
    ]
