# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0068_remove_marketbotrank_trailing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbotrank',
            name='trailing_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='trailing price'),
        ),
    ]
