# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0069_marketbotrank_trailing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='is_trailing_stop_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketorderlog',
            name='type',
            field=models.CharField(choices=[('CREATE_ORDER', 'Ордер создан'), ('FILLED_ORDER', 'Ордер выполнен'), ('MAX_PRICE_FIXED', 'MaxPrice зафиксирована'), ('MAX_PRICE_UPDATED', 'MaxPrice обновлена'), ('STOP_LOSS', 'Сработал Stop Loss'), ('TRAILING_FALL', 'Сработал Trailing Fall'), ('TRAILING_STOP_LOSS', 'Сработал Trailing Stop Loss'), ('MAX_PRICE_FIXED', 'Trailing Price зафиксирована'), ('MAX_PRICE_UPDATED', 'Trailing Price обновлена'), ('STOP_LOSS', 'Установлен Stop Loss')], default='CREATE_ORDER', max_length=25),
        ),
    ]
