# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0070_auto_20180601_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='status_cancel',
            field=models.CharField(blank=True, choices=[('TIME', 'По времени'), ('STOP_LOSS', 'Stop Loss'), ('TRAILING_STOP_LOSS', 'Trailing Stop Loss')], max_length=25, null=True),
        ),
    ]
