# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0072_botstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='kind',
            field=models.CharField(choices=[('MAIN', 'Основной'), ('SAFETY', 'Страховочный'), ('FIX', 'Фиксирующий')], default='MAIN', max_length=10),
        ),
    ]
