# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 10:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0073_marketmyorder_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_orders_active_count',
            field=models.SmallIntegerField(default=2, verbose_name='Количество страховых ордеров'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_orders_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.99999999999999954748111825886258685613938723690807819366455078125E-8'), max_digits=5, verbose_name='Объем страховочных ордеров'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_orders_max_count',
            field=models.SmallIntegerField(default=5, verbose_name='Максимальное количество страховых ордеров'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_price_change',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Отклонение цены для выставления страховочного ордера (% от стоимости начального ордера)'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_ratio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Множитель объема страховочных ордеров'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_start_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.99999999999999954748111825886258685613938723690807819366455078125E-8'), max_digits=5, verbose_name='Объем стартового ордера'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='average_safety_step',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Множитель шага страховочных ордеров'),
        ),
    ]
