# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0074_auto_20180613_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='is_average_safety',
            field=models.BooleanField(default=False, verbose_name='Статегия усреднения'),
        ),
    ]
