# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 10:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0075_marketbot_is_average_safety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketbot',
            name='average_safety_orders_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('9.99999999999999954748111825886258685613938723690807819366455078125E-8'), max_digits=24, verbose_name='Объем страховочных ордеров'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='average_safety_price_change',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=24, verbose_name='Отклонение цены для выставления страховочного ордера (% от стоимости начального ордера)'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='average_safety_start_order_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('9.99999999999999954748111825886258685613938723690807819366455078125E-8'), max_digits=24, verbose_name='Объем стартового ордера'),
        ),
    ]
