# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


def set_default_exchange(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    model_exchange = apps.get_model("trading", "Exchange")

    model_exchange.objects.get_or_create(name='Bittrex', code='bittrex')
    model_exchange.objects.get_or_create(name='Binance', code='binance')


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0076_auto_20180613_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('code', models.CharField(help_text='Для использовния в коде', max_length=100, verbose_name='код')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='сайт')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'биржы',
                'db_table': 'trading_exchange',
                'verbose_name': 'биржа',
            },
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='average_safety_orders_active_count',
            field=models.SmallIntegerField(default=2, verbose_name='Количество активных страховых ордеров'),
        ),
        migrations.RunPython(set_default_exchange),
    ]
