# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_default_exchange(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    model_exchange = apps.get_model("trading", "Exchange")
    model_bot = apps.get_model("trading", "MarketBot")

    exchange, created = model_exchange.objects.get_or_create(name='Bittrex', code='bittrex')
    bots = model_bot.objects.all()
    for bot in bots:
        bot.exchange = exchange
        bot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0077_auto_20180721_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Exchange'),
        ),
        migrations.RunPython(set_default_exchange),
    ]
