# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_default_code(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    model_market = apps.get_model("trading", "Market")

    markets = model_market.objects.all()
    for market in markets:

        market.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0078_marketbot_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='code',
            field=models.CharField(default='-', max_length=100, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Exchange'),
        ),
        migrations.RunPython(set_default_code),
    ]
