# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-05 09:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0079_auto_20180729_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('exchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Exchange')),
                ('market', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Market')),
            ],
            options={
                'verbose_name': 'Настройки пары на бирже',
                'verbose_name_plural': 'Настройки пары на бирже',
                'db_table': 'trading_market_settings',
            },
        ),
    ]
