# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0080_marketsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketsettings',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='trading.Market'),
        ),
    ]
