# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0081_auto_20180810_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmyorder',
            name='ext_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
