# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0082_marketmyorder_ext_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmyorder',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
