# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0083_auto_20181129_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_active_binance',
            field=models.BooleanField(default=False),
        ),
    ]
