# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0084_market_is_active_binance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMarketFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.CharField(max_length=100, verbose_name='название')),
                ('maxPrice', models.CharField(max_length=100)),
                ('minPrice', models.CharField(max_length=100)),
                ('tickSize', models.CharField(max_length=100)),
                ('p_avgPriceMins', models.CharField(max_length=100)),
                ('multiplierUp', models.CharField(max_length=100)),
                ('multiplierDown', models.CharField(max_length=100)),
                ('maxQty', models.CharField(max_length=100)),
                ('minQty', models.CharField(max_length=100)),
                ('stepSize', models.CharField(max_length=100)),
                ('minNotional', models.CharField(max_length=100)),
                ('n_avgPriceMins', models.CharField(max_length=100)),
                ('applyToMarket', models.CharField(max_length=100)),
                ('limit', models.CharField(max_length=100)),
                ('maxNumAlgoOrders', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Проверка фильтров',
                'verbose_name_plural': 'Пповерка фильтров',
                'db_table': 'check_market_filter',
            },
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Exchange', verbose_name='Биржа'),
        ),
    ]
