# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0087_auto_20190107_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_amount', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Начальный баланс')),
                ('free', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Текущий баланс')),
                ('locked', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Текущий баланс')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_currencies', to='trading.Currency', verbose_name='Валюта')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='trading.Exchange', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'валюта на бирже',
                'verbose_name_plural': 'валюты на бирже',
                'db_table': 'trading_exchange_currency',
            },
        ),
        migrations.CreateModel(
            name='ExchangeCurrencyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Доступно')),
                ('locked', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Заблокировано')),
                ('operation', models.CharField(choices=[('BUY', 'Покупка'), ('SELL', 'Продажа'), ('CHECK', 'Проверка')], default='CHECK', max_length=10)),
                ('exchange_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.ExchangeCurrency', verbose_name='Валюта')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketMyOrder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'статистика валюты на бирже',
                'verbose_name_plural': 'статистика валют на бирже',
                'db_table': 'trading_exchange_currency_statistic',
            },
        ),
        migrations.AlterUniqueTogether(
            name='exchangecurrency',
            unique_together=set([('currency', 'exchange')]),
        ),
    ]
