# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0088_auto_20200509_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecurrencystatistic',
            name='exchange_currency',
        ),
        migrations.AddField(
            model_name='exchangecurrencystatistic',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Currency', verbose_name='Валюта'),
        ),
    ]
