# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0089_auto_20200522_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecurrencystatistic',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='курс USDT'),
        ),
        migrations.AddField(
            model_name='exchangecurrencystatistic',
            name='total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Всего'),
        ),
        migrations.AddField(
            model_name='exchangecurrencystatistic',
            name='usdt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='Всего USDT'),
        ),
    ]
