# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-01-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0090_auto_20200621_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('btc', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BTC')),
                ('bnb', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BTC')),
                ('rate_bnb', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BTC')),
                ('usdt', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BTC')),
                ('rate_usdt', models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BTC')),
            ],
            options={
                'verbose_name': 'статистика баланса',
                'db_table': 'trading_history_balance',
            },
        ),
    ]
