# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-01-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0091_historybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='historybalance',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.MarketMyOrder'),
        ),
    ]
