# Generated by Django 3.2.7 on 2021-11-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0092_historybalance_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historybalance',
            options={'verbose_name': 'статистика баланса', 'verbose_name_plural': 'статистика балансов'},
        ),
        migrations.AddField(
            model_name='marketbot',
            name='block_panic_sell_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время остановки бота после Panic Sell'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='is_block_panic_sell',
            field=models.BooleanField(default=False, verbose_name='Бот остановлен после Panic Sell'),
        ),
        migrations.AlterField(
            model_name='bottestorder',
            name='ticker_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historybalance',
            name='bnb',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='BNB'),
        ),
        migrations.AlterField(
            model_name='historybalance',
            name='rate_bnb',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='rate BNB'),
        ),
        migrations.AlterField(
            model_name='historybalance',
            name='rate_usdt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='rate USDT'),
        ),
        migrations.AlterField(
            model_name='historybalance',
            name='usdt',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=24, verbose_name='USDT'),
        ),
        migrations.AlterField(
            model_name='marketbot',
            name='rank_base_currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_base': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.currency', verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='marketbotrank',
            name='ticker_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='get_order_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketmyorder',
            name='ticker_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorderlog',
            name='bot_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorderlog',
            name='ticker_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketsettings',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
