# Generated by Django 3.2.7 on 2021-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0093_auto_20211106_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='strategy',
            field=models.CharField(choices=[('long', 'Long (на росте)'), ('short', 'Short (на падении)')], default='long', max_length=5, verbose_name='Стратегия'),
        ),
    ]
