# Generated by Django 3.2.7 on 2022-07-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0094_marketbot_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketbot',
            name='strategy',
        ),
    ]
