# Generated by Django 3.2.7 on 2024-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0096_marketbot_is_sword_or_hummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbot',
            name='ut_atr_period',
            field=models.SmallIntegerField(default=7, verbose_name='Ut bot ATR_PERIOD'),
        ),
        migrations.AddField(
            model_name='marketbot',
            name='ut_sensitivity',
            field=models.SmallIntegerField(default=2, verbose_name='Ut bot SENSITIVITY'),
        ),
    ]
