# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('method', models.CharField(default='GET', max_length=50)),
            ],
            options={
                'db_table': 'test_webhook',
            },
        ),
    ]
